# network.host: 0.0.0.0

# this value is required because we set "network.host"
# be sure to modify it appropriately for a production cluster deployment
discovery.zen.minimum_master_nodes: 1
# bootstrap.memory_lock: true

node.master: true
node.ingest: true
node.data: true